package dimension

import (
	"strings"
)

type Format string

func (s Format) Convert() string {
	var lookup = map[string]string{
		"belvederes":       "Belvedere",
		"bondadosos":       "Bondadoso",
		"brevas jlp":       "Breva JLP",
		"britanicas":       "Britanica",
		"cadetes":          "Cadete",
		"campanas":         "Campana",
		"caprichos":        "Capricho",
		"carlotas":         "Carlota",
		"cazadores":        "Cazador",
		"centro finos":     "Centro Fino",
		"coloniales":       "Colonial",
		"conchitas":        "Conchita",
		"conservas jlp":    "Conserva JLP",
		"conserva jlp":     "Conserva JLP",
		"conservas":        "Conserva",
		"coronas grandes":  "Corona Grande",
		"coronas":          "Corona",
		"coronitas":        "Coronita",
		"corticas":         "Cortica",
		"cosacos":          "Cosaco",
		"cremas":           "Crema",
		"cristales":        "Cristal",
		"culebras":         "Culebra",
		"cupidos":          "Cupido",
		"dalias":           "Dalia",
		"deleites":         "Deleite",
		"delicados extra":  "Delicado Extra",
		"delicados":        "Delicado",
		"deliciosos":       "Delicioso",
		"diademas":         "Diadema",
		"dinoras":          "Dinora",
		"eminentes":        "Eminente",
		"entreactos":       "Entreacto",
		"epicures":         "Epicure",
		"esplendido":       "Esplendido",
		"estupendos":       "Estupendo",
		"exitosos":         "Exitoso",
		"exquisitos":       "Exquisito",
		"favoritos":        "Favorito",
		"franciscanos":     "Franciscano",
		"franciscos":       "Francisco",
		"generosos":        "Generoso",
		"geniales":         "Genial",
		"genios":           "Genio",
		"gigantes":         "Gigante",
		"gustosos":         "Gustoso",
		"imperiales":       "Imperial",
		"infantes":         "Infante",
		"maestros":         "Maestro",
		"magicos":          "Magico",
		"mananitas":        "Mananita",
		"marevas":          "Mareva",
		"marinas":          "Marina",
		"minutos":          "Minuto",
		"nacionales jlp":   "Nacional JLP",
		"noblezas":         "Nobleza",
		"palmas":           "Palma",
		"palmitas":         "Palmita",
		"panetelas largas": "Panetela Larga",
		"panetelas":        "Panetela",
		"parejos":          "Parejo",
		"perfectos":        "Perfecto",
		"perlas":           "Perla",
		"petit belicosos":  "Petit Belicoso",
		"petit cetros":     "Petit Cetro",
		"petit pirámides":  "Petit Pirámide",
		"piramide":         "Pirámide",
		"pirámides":        "Pirámide",
		"pirámide extra":   "Pirámide Extra",
		"pirámides extra":  "Pirámide Extra",
		"placeras":         "Placera",
		"prominentes":      "Prominente",
		"pyramide":         "Pirámide",
		"pyramides":        "Pirámide",
		"reyes":            "Rey",
		"robustos no. 2":   "robusto no. 2",
		"robustos":         "Robusto",
		"romeos":           "Romeo",
		"salomones":        "Salomón",
		"short pirámides":  "Short Pirámide",
		"short salomones":  "Short Salomón",
		"sobresalientes":   "Sobresaliente",
		"tacos":            "Taco",
		"topes":            "Tope",
		"toppers":          "Topper",
		"torres":           "Torre",
		"trabucos":         "Trabuco",
		"vegueritos":       "Veguerito",
		"venerables":       "Venerable",
	}

	tmp := strings.ToLower(string(s))
	o, ok := lookup[tmp]
	if !ok {
		o = toCapFirstLetters(tmp)
	}
	return o
}
