package dimension

import "strings"

type TobaccoType string

func (s TobaccoType) Convert() string {
	lookup := map[string]string{
		"altepec":                      "Altepec",
		"arapiraca":                    "Arapiraca",
		"bahia":                        "Bahia",
		"bandtabak":                    "Mixed",
		"mixed":                        "Mixed",
		"mix":                          "Mixed",
		"bezuki":                       "Bezuki",
		"broadleaf":                    "Broadleaf",
		"broadleaf claro":              "Broadleaf Claro",
		"cameroon":                     "Cameroon",
		"cameroon seed":                "Cameroon Seed",
		"candela":                      "Candela",
		"candela/maduro":               "Candela/Maduro",
		"cibao":                        "Cibao",
		"cibao valley":                 "Cibao Valley",
		"colorado":                     "Colorado",
		"colorado claro":               "Colorado Claro",
		"colorado maduro":              "Colorado Maduro",
		"condega":                      "Condega",
		"connecticut":                  "Connecticut",
		"connecticut broadleaf":        "Connecticut Broadleaf",
		"connecticut broadleaf maduro": "Connecticut Broadleaf Maduro",
		"connecticut seed":             "Connecticut Seed",
		"connecticut shade":            "Connecticut Shade",
		"corojo":                       "Corojo",
		"corojo maduro":                "Corojo Maduro",
		"corojo oscuro":                "Corojo Oscuro",
		"cotui":                        "Cotui",
		"criollo":                      "Criollo",
		"cubra":                        "Cubra",
		"ecuador":                      "Ecuador",
		"ecuador claro":                "Ecuador Claro",
		"ecuador desflorado":           "Ecuador Desflorado",
		"ecuador sumatra":              "Ecuador Sumatra",
		"esteli":                       "Esteli",
		"h 2000":                       "H2000",
		"h-2000":                       "H2000",
		"h2000":                        "H2000",
		"habano oscuro":                "Habano Oscuro",
		"honduran trojes":              "Honduran Trojes",
		"indonesia":                    "Indonesia",
		"jalapa":                       "Jalapa",
		"jalapa sun grown":             "Jalapa Sun Grown",
		"jamastran":                    "Jamastran",
		"java":                         "Java",
		"java besuki":                  "Java Besuki",
		"kentucky":                     "Kentucky",
		"kentucky dark fired":          "Kentucky Dark Fired",
		"kentucky fire cured":          "Kentucky Fire Cured",
		"ligero":                       "Ligero",
		"maduro":                       "Maduro",
		"mata fina":                    "Mata Fina",
		"mata norte":                   "Mata Norte",
		"medio tiempo":                 "Medio Tiempo",
		"mexico":                       "Mexico",
		"naturdeckblatt":               "Naturdeckblatt",
		"negrito":                      "Negrito",
		"olancho san augustin":         "Olancho San Augustin",
		"olor":                         "Olor",
		"ometepe":                      "Ometepe",
		"oscuro":                       "Oscuro",
		"otapan negro ultimo corte":    "Otapan Negro Ultimo Corte",
		"pennsylvania":                 "Pennsylvania",
		"piloto":                       "Piloto",
		"rosado":                       "Rosado",
		"san andres maduro":            "San Andres Maduro",
		"san andres negro":             "San Andres Negro",
		"san andrés":                   "San Andrés",
		"san andrés & candela":         "San Andrés & Candela",
		"sancti spiritus":              "Sancti Spiritus",
		"sandblatt":                    "Sand leaf",
		"sand blatt":                   "Sand leaf",
		"sand-blatt":                   "Sand leaf",
		"sand leaf":                    "Sand leaf",
		"sand-leaf":                    "Sand leaf",
		"seco":                         "Seco",
		"shade grown namanji":          "Shade Grown Namanji",
		"subido shade":                 "Subido Shade",
		"sumatra":                      "Sumatra",
		"sumatra maduro":               "Sumatra Maduro",
		"sun grown":                    "Sun Grown",
		"sun grown cameroon":           "Sun Grown Cameroon",
		"sungrown":                     "Sun grown",
		"sun-grown":                    "Sun grown",
		"viso":                         "Viso",
		"viso 98":                      "Viso 98",
		"viso jalapa":                  "Viso Jalapa",
		"yamasa":                       "Yamasa",
	}
	v := string(s)
	tmp := strings.ToLower(v)
	o, ok := lookup[tmp]
	if !ok {
		o = v
	}
	return o
}
